### ISSUE TITLE
Issue - dwm crashing caused by some apps

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#10]
I have noticed that when using Microsoft access 2016 and switching through tables too fast causes dwm to crash,  the cause is uDWM.dll, I also noticed the crashes when I exit GTA V. Might link a video tomorrow

**Comment by nopahc4** [comment]
wanted to record this, but it looks like its no longer happening, will update if i get a crash again

**Comment by akaydev-coder** [comment]
I can confirm this but could not locate the trigger for it. 
@Maplespe did you implement a debug switch and active logging that I/we can locate the origin of the crash?

**Comment by Maplespe** [comment]
@akaydev-coder You should be able to view the System Event Manager log dwm crash specific information.

**Comment by nopahc4** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/365a5118-ebcd-439a-846f-5bdddf6c78fe)
yes, it logs it in event viewer> windows logs> applications, unfortunately i don't think my logs will be able to help since they're in polish

**Comment by CallyHam** [comment]
i've noticed crashes sometimes too and so far it seems to be mostly when im doing things related to explorer, sometimes happens with other programs too though but for the most part it seems random, here's one of the event viewer logs, this time it happened when i opened a program from the desktop
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/66b691a0-39fc-4d15-a455-7d4642e1ad44)

**Comment by akaydev-coder** [comment]
Error:
```
Name der fehlerhaften Anwendung: dwm.exe, Version: 10.0.19041.3636, Zeitstempel: 0x6e55ef4a
Name des fehlerhaften Moduls: udwm.dll, Version: 10.0.19041.3758, Zeitstempel: 0x96a62465
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000019174
ID des fehlerhaften Prozesses: 0xd30
Startzeit der fehlerhaften Anwendung: 0x01da4a3fd3262456
Pfad der fehlerhaften Anwendung: C:\WINDOWS\system32\dwm.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\udwm.dll
Berichtskennung: 1cf2a60a-76fd-4acd-95ca-8255ca3edfc3
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```
Followed by Warning:
```
Der Desktopfenster-Manager-Prozess wurde beendet. (Prozessexitcode: 0xc0000005, Neustartzähler: 1, ID des primären Anzeigegeräts: NVIDIA GeForce GTX 1080 Ti)
```

**Comment by Maplespe** [comment]
We found a stack overflow that could be the cause of the crash, we have fixed it in the new version, please try the new version to see the stability.

**Comment by NotJorrd** [comment]
> We found a stack overflow that could be the cause of the crash, we have fixed it in the new version, please try the new version to see the stability.

i have experienced another crash after installing the version in #18

**Comment by nopahc4** [comment]
> We found a stack overflow that could be the cause of the crash, we have fixed it in the new version, please try the new version to see the stability.

thanks, will let you know once something happens again

**Comment by Longhorn004** [comment]
Using Windows 10 Home 22H2, uDWM still crashes on 1.0.3.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/119104342/9afb8151-c4f0-41bc-959e-e05790c9cb9a)

**Comment by nopahc4** [comment]
> Using Windows 10 Home 22H2, it still crashes on 1.0.3. ![image](https://private-user-images.githubusercontent.com/119104342/298370371-9afb8151-c4f0-41bc-959e-e05790c9cb9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjY1MjMsIm5iZiI6MTcwNTgyNjIyMywicGF0aCI6Ii8xMTkxMDQzNDIvMjk4MzcwMzcxLTlhZmI4MTUxLWM0ZjAtNDFiYy05NTllLWUwNTc5MGM5Y2I5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwODM3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjU1M2UxMjhmODM1YjI0ODMwYWFiNmE4MTE0ODBmMTQyNzVlZGZhMTY3NWM5MTY4MDVhYWNhMjAwMmNmOWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zkJ0jh_rVDUZcO8pJ7rgeR2_VngZR4vYSYVS8mc1Chw)

can confirm, but for me it only crashed while changing some settings

**Comment by Maplespe** [comment]
Unfortunately this information is almost useless, a fault dump file would have been useful.

**Comment by Longhorn004** [comment]
> Unfortunately this information is almost useless, a fault dump file would have been useful.

I currently don't have an dump file, but I will look at it soon.

**Comment by akaydev-coder** [comment]
> Unfortunately this information is almost useless, a fault dump file would have been useful.

I set up Windows to  create a crashdump file. I have no idea which action is required to  trigger the crash again - I use a combination of StartisBack | ExplorerPatcher ( own fork with fixed glass command bar on windows 10 ) | ONE and TranslucentFlyouts - also Secure UXtheme Patcher runs in the background for non signed themes. My system is not the a good reference to find or fix the problem but if a dump helps anyway I  will upload it.

--------------------------------------------------------------------------------------

Offtopic: Did you accept donations or tips? Couldn't find a link or something else. Since BigMuscle is gone ( and wit him Glass8 ) this is the first project which brings back the great Glass/DWM effect. I can't spend much but better then do nothing

Using Stardock Curtains until you released DWMBlurGlass which was ok but not the same and Stardock lacks with updates or guides

**Comment by Maplespe** [comment]
@akaydev-coder Thank you for your support, but I don't have international sponsorship channels, only Chinese payment methods such as WeChat and Aifadian in my website.

**Comment by akaydev-coder** [comment]
@Maplespe oh  sad - Well that's impossible for me, tried to register at QQ and WeChat in the past because I try to support other developer as well but without luck.

Ontopic, Windows has not created a crashdump file for dwm.exe but I got WER report after I enable it. I hope that is useful:

<details>
<summary>Details</summary>

```
Version=1
EventType=APPCRASH
EventTime=133503215623304682
ReportType=2
Consent=1
UploadTime=133503215625724679
ReportStatus=268435456
ReportIdentifier=2778ad42-e2b9-4cbd-a903-1caf92843971
IntegratorReportIdentifier=c66108aa-10c7-4120-9a0d-a4245530bb61
Wow64Host=34404
NsAppName=dwm.exe
OriginalFilename=dwm.exe
AppSessionGuid=00000d28-0001-0012-78fd-b2c7744cda01
TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!0000ec039023c2d1947d01e2f56d2dd726cf0645934f!dwm.exe
TargetAppVer=2028//08//29:01:32:58!20c95!dwm.exe
BootId=4294967295
TargetAsId=62
UserImpactVector=784
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=561592b787fec27071319c4d1025eb48
Response.BucketTable=4
Response.LegacyBucketId=1238943227300932424
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=dwm.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=10.0.19041.3636
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=6e55ef4a
Sig[3].Name=Fehlermodulname
Sig[3].Value=udwm.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=10.0.19041.3758
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=96a62465
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=0000000000019174
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.19045.2.0.0.256.161
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=e234
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=e23487a1eec4aa3a33350477454f6a45
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=c7e1
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=c7e1dd45a1c6160fd79bf4e77b16c019
UI[2]=C:\WINDOWS\system32\dwm.exe
UI[5]=Schließen
UI[8]=Desktop Window Manager wurde beendet und geschlossen.
UI[9]=Die Anwendung wird aufgrund eines Problems nicht mehr richtig ausgeführt. Sie erhalten Nachricht, wenn eine Lösung verfügbar ist.
UI[10]=S&chließen
LoadedModule[0]=C:\WINDOWS\system32\dwm.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\Program Files (x86)\Common Files\Kaspersky Lab\K4W-21-16\klhk\klhk_x64\klhkum.{58.0.11.0}.{1B8FAA1A-F8D0-43DB-A748-025BB9E7C5B4}.dll
LoadedModule[6]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[7]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[8]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[9]=C:\WINDOWS\System32\sechost.dll
LoadedModule[10]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[11]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[12]=C:\WINDOWS\System32\gdi32.dll
LoadedModule[13]=C:\WINDOWS\System32\win32u.dll
LoadedModule[14]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[15]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[16]=C:\WINDOWS\System32\USER32.dll
LoadedModule[17]=C:\WINDOWS\System32\combase.dll
LoadedModule[18]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\dwmredir.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\udwm.dll
LoadedModule[21]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[22]=C:\WINDOWS\system32\CoreMessaging.dll
LoadedModule[23]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[24]=C:\WINDOWS\system32\dwmcore.dll
LoadedModule[25]=C:\WINDOWS\system32\CoreUIComponents.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[27]=C:\WINDOWS\System32\SHCORE.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[30]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[31]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[32]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[33]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[34]=C:\WINDOWS\system32\d2d1.dll
LoadedModule[35]=C:\WINDOWS\system32\D3DCOMPILER_47.dll
LoadedModule[36]=C:\WINDOWS\system32\CRYPTSP.dll
LoadedModule[37]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[38]=C:\WINDOWS\system32\UMPDC.dll
LoadedModule[39]=C:\WINDOWS\system32\XmlLite.dll
LoadedModule[40]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\dwmghost.dll
LoadedModule[42]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[43]=C:\WINDOWS\system32\avrt.dll
LoadedModule[44]=C:\WINDOWS\SYSTEM32\ism.dll
LoadedModule[45]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[46]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[47]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[48]=C:\WINDOWS\system32\PROPSYS.dll
LoadedModule[49]=C:\WINDOWS\system32\HID.DLL
LoadedModule[50]=C:\WINDOWS\system32\NInput.dll
LoadedModule[51]=C:\WINDOWS\system32\MSASN1.dll
LoadedModule[52]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[53]=C:\Windows\System32\windowmanagementapi.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
LoadedModule[55]=C:\WINDOWS\system32\WindowsCodecs.dll
LoadedModule[56]=C:\WINDOWS\System32\UIAnimation.dll
LoadedModule[57]=C:\Windows\System32\DispBroker.Desktop.dll
LoadedModule[58]=C:\Windows\System32\mscms.dll
LoadedModule[59]=C:\Windows\System32\USERENV.dll
LoadedModule[60]=C:\Windows\System32\ColorAdapterClient.dll
LoadedModule[61]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[62]=C:\WINDOWS\system32\CRYPTBASE.dll
LoadedModule[63]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[64]=C:\Windows\System32\ActXPrxy.dll
LoadedModule[65]=C:\Windows\System32\DispBroker.dll
LoadedModule[66]=C:\Windows\System32\Windows.Graphics.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\gpapi.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\wtsapi32.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[70]=c:\windows\system32\gameinput.dll
LoadedModule[71]=C:\Windows\System32\Windows.Gaming.Input.dll
LoadedModule[72]=C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
LoadedModule[73]=C:\Windows\System32\Windows.System.UserDeviceAssociation.dll
LoadedModule[74]=C:\Windows\System32\usermgrproxy.dll
LoadedModule[75]=C:\WINDOWS\system32\D3D10Warp.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\cryptnet.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\drvstore.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\devobj.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\wldp.dll
LoadedModule[81]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[82]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[83]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[84]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_3c2bd4a1ec6d228e\nvldumdx.dll
LoadedModule[85]=C:\WINDOWS\system32\VERSION.dll
LoadedModule[86]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_3c2bd4a1ec6d228e\nvwgf2umx.dll
LoadedModule[87]=C:\WINDOWS\System32\ole32.dll
LoadedModule[88]=C:\WINDOWS\system32\WINMM.dll
LoadedModule[89]=C:\WINDOWS\system32\Cabinet.dll
LoadedModule[90]=C:\WINDOWS\system32\TextShaping.dll
LoadedModule[91]=G:\root.appbox\WinUI\DWMBlurGlass\DWMBlurGlassExt.dll
LoadedModule[92]=C:\WINDOWS\system32\dbghelp.dll
LoadedModule[93]=C:\Windows\System32\Windows.UI.Xaml.Controls.dll
LoadedModule[94]=C:\Windows\System32\Bcp47Langs.dll
LoadedModule[95]=C:\Windows\System32\Windows.UI.Xaml.dll
LoadedModule[96]=C:\Windows\System32\iertutil.dll
LoadedModule[97]=C:\WINDOWS\system32\wuceffects.dll
LoadedModule[98]=C:\WINDOWS\System32\MSCTF.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=TpToken
State[1].Value=3.6687d3cf1ce465c8625e36c553a8498f.01da54534a827869.meta={cabrequesttype,0};meta={ibucket,1238943227300932424};meta={ieventtype,140};meta={reportid,c66108aa10c741209a0da4245530bb61};meta={rules,v=1}
State[2].Key=TpTokenExp
State[2].Value=133511855669934185
State[3].Key=TpWatsonBucketId
State[3].Value=561592b787fec27071319c4d1025eb48
State[4].Key=TpWatsonLegacyBucketId
State[4].Value=1238943227300932424
State[5].Key=TpWatsonBucketTable
State[5].Value=4
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=3992
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=161
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=8263
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.3636.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=65457
OsInfo[19].Key=svolsz
OsInfo[19].Value=465
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.3992.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[30].Value=bbbb7dbc-e013-47b9-80ea-8b76f0a23960
OsInfo[31].Key=edition
OsInfo[31].Value=ProfessionalWorkstation
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:117B9872,FX:119E26AD,FX:124117A5,FX:124B38D0,FX:127FC878,FX:1283FFE8,FX:12840617,FX:128979F9,FX:128EBD7E,FX:129135BB,FX:129E053F,FX:12A74DB5,FX:12B8450E,FX:12BD6E73,FX:12C3331B,FX:12C7D66E,FX:12CDE644,FX:12D1574C,FX:12D281C4
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=Desktop Window Manager
AppPath=C:\WINDOWS\system32\dwm.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=EC582D63A2B205DE573333C581C1FBDD
MetadataHash=291230453
```

</details>

**Comment by akaydev-coder** [comment]
Got it!

@Maplespe got 2 Dumps within 2 Seconds, I couldn't upload it on Github so find out the link:

<details>
<summary>Details</summary>

[DWM.7z](https://www.subsoil-sandsteinhöhlen.net/dwm.7z)

</details>

Please let me know if you downloaded it, because I want to delete it.

**Comment by Maplespe** [comment]
@akaydev-coder Thanks, downloaded.

**Comment by nope312** [comment]
I also have this problem

**Comment by ZyrusplaysAnimations** [comment]
DWM also crashes on lock screen after waking up from sleep/hibernation.

**Comment by Maplespe** [comment]
The new version has worked for hours without crashing and I think it is more stable.

**Comment by CallyHam** [comment]
i can definitely agree since the new version i havent crashed once

**Comment by NotJorrd** [comment]
so far so good on the new version, just gotta keep using it

**Comment by akaydev-coder** [comment]
Confirmed @CallyHam @NotJorrd @Maplespe
