### ISSUE TITLE
[FIXED IN 2.3.2] CustomBlur (IComposition) is broken on build 26x00.7019 (KB5067036) and later

### ISSUE THREAD

**Issue by YMica-OSE** [Maplespe/DWMBlurGlass#603]
## **Describe the bug:**
After updating to build 26100/26200.7019 (KB5067036 aka the 2025-10 Preview CU for Windows 11 24H2/25H2), the default CustomBlur method no longer works properly, instead **only showing clear transparency (no blur, no aero, just the color).**   
Title bars & window frames affected by the Override DWMAPI effect does not exhibit this issue. 

## **To Reproduce:**
Just install update [KB5067036](https://support.microsoft.com/en-us/topic/october-28-2025-kb5067036-os-builds-26200-7019-and-26100-7019-preview-ec3da7dc-63ba-4b1d-ac41-cf2494d2123a). 

## **UPDATE - To fix:**
Update to [version 2.3.2](https://github.com/Maplespe/DWMBlurGlass/releases/tag/2.3.2). 
Do note that at the moment this is still in beta, so do expect other issues. The fix may also require you to install the 26200 (25H2) enablement package - [KB5054156](https://support.microsoft.com/en-us/topic/kb5054156-feature-update-to-windows-11-version-25h2-by-using-an-enablement-package-4d307e2d-3028-4323-bb46-552cff491643#id0epbf=windows_update).
![Image](https://github.com/user-attachments/assets/79499138-dc7a-4927-bdf7-8f464e056c0d)

## **Screenshots & Demo:**
![Image](https://github.com/user-attachments/assets/24437122-f22e-4d87-9a9e-9ca27d1fe98c)

https://github.com/user-attachments/assets/76dadc46-36a8-474f-b495-4f2ab8504925

## **Additional information:**
 - OS Version Tested : 26200.7019
 - Software Version : 2.3.1

## **What other third-party software do you use:**
None

## **Additional context:**
From other related reports, it seems whatever change that caused this and similar bugs was introduced a few updates before this one, so the affected builds could range from 26x00.6972 to 26x00.7019+.
<ins>**Other reports with this same issue:**</ins> #597, #595, #608, #609, #617, #618

**Comment by LeeBinder** [comment]
see my comment https://github.com/Maplespe/DWMBlurGlass/issues/595#issuecomment-3470506432

**Comment by UnfallenSeaMoon** [comment]
I have the same problem.Please remind me if this problem is fixed

**Comment by Sostay** [comment]
same issue

**Comment by 0-BlackSpectrum-0** [comment]
Same issue, I'm on Windows 11 25H2, some apps like old windows image viewer, winaero and other apps have just transparent effect instead of mica which I've selected, I just installed this app yesterday, and running latest version of it as of 9 November 2025.

I also use your Explorer Mica effect app and Windhawk, if it helps

**Comment by Pamlau** [comment]
Hey guys, I wanna point out that I fixed mine simply by adjusting the opacity back to 0%, it has always been at 0% but for some reason with the windows update it set it to 50% opacity or so, maybe try readjusting the settings again just to make sure

<img width="484" height="722" alt="Image" src="https://github.com/user-attachments/assets/c83fec2b-95f8-42d4-acfe-3474aff76545" />

**Comment by BothSamuel** [comment]
The only temporary solution is to use Mica For Everyone, and in the "Global" rule, change the Background type to "Acrylic". At least in my case, I'm still using DWMBlurGlass to configure the title bar color, blur level and set the title bar buttons to small, like in Windows 7.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c50168b7-faf7-42e5-9824-869dca42140b" />

Mica for everyone config
<img width="886" height="788" alt="Image" src="https://github.com/user-attachments/assets/e130a096-f8b2-4479-bcbd-ee6ddc8df053" />

**Comment by jgalvez21** [comment]
mica foreveryone i cannot get it to work on firefox... toolkit.legacyUserProfileCustomizations.stylesheets

**Comment by diarrhea3** [comment]
This is still happening on the 2.3.2 beta. I'm running 26100.7171, but I believe the 26100 vs 26200 part does not matter as it's the same on both.

**Comment by Skyyblaze** [comment]
@diarrhea3 It does actually, I had the same issue as you but updating to 26200 fixed it, the fixes in the latest beta of DWMBlurGlass specifically target 25H2.

**Comment by YMica-OSE** [comment]
Can confirm that 2.3.2 Beta 1 has fixed this bug. Thanks everyone for the feedbacks and @Maplespe for working on the fix. I have updated the issue name + description and will now close it.

**Comment by diarrhea3** [comment]
@Skyyblaze That’s good to know thanks. Well I’m using LTSC 2024 which can’t be updated beyond 26100 so I guess I’m stuck with it, unless the developer fixes it for 24H2 as well.

**Comment by Skyyblaze** [comment]
@diarrhea3 I see that's unfortunate, maybe the final release of the 2.3.2 will work eventually.
